source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxRealm_Example' do
  platform :ios, '8.0'
  pod 'RxRealm', :path => '../'
  pod 'RxSwift',    '~> 3.0.0-beta.2'
  pod 'RxCocoa',    '~> 3.0.0-beta.2'
  pod 'RealmSwift', '~> 2.0'
end

target 'RxRealm_Tests' do
  platform :ios, '8.0'
  pod 'RxTests',    '~> 3.0.0-beta.2'
  pod 'RealmSwift', '~> 2.0'
  pod 'RxRealm', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
