source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def common
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RealmSwift', '~> 4.0'
end

target 'RxRealm_Example' do
  platform :ios, '9.0'
  common
  pod 'RxRealm', :path => '../'
end

target 'RxRealm_Tests' do
  platform :ios, '9.0'
  common
  pod 'RxBlocking', '~> 5.0'
  pod 'RxRealm', :path => '../'
end
