source "https://cdn.cocoapods.org/"
project "RxRealmDemo.xcodeproj"
use_frameworks!

def common
  pod "RxRealm", :path => "../"
end

def common_tests
  pod "RxBlocking", "~> 5.1"
end

target "RxRealmDemo-iOS" do
  platform :ios, "9.0"
  common
end

# target "RxRealmDemo-macOS" do
#   platform :osx, "10.12"
#   common
# end

# target "RxRealmDemo-tvOS" do
#   platform :tvos, "9.0"
#   common
# end
