name: Lint, build and test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Resolve dependencies
        run: |
          brew bundle
          bundle

      - name: Danger
        run: |
          bundle exec danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore SPM Cache
        uses: actions/cache@v1
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test (SPM)
        run: |
          swift build
          swift test

      - name: Generate Xcodeproj
        run: |
          xcodegen

      - name: Restore Carthage Cache
        uses: actions/cache@v1
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-

      - name: Resolving Carthage dependencies
        run: |
          set -euo pipefail

          xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
          trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

          # For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
          # the build will fail on lipo due to duplicate architectures.

          CURRENT_XCODE_VERSION=$(xcodebuild -version | grep "Build version" | cut -d' ' -f3)
          echo "EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$CURRENT_XCODE_VERSION = arm64 arm64e armv7 armv7s armv6 armv8" >> $xcconfig

          echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
          echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

          export XCODE_XCCONFIG_FILE="$xcconfig"
          carthage update --cache-builds --new-resolver --configuration Debug

      - name: Testing RxRealm iOS framework
        run: |
          xcodebuild test -scheme 'RxRealm iOS' -project 'RxRealm.xcodeproj' -sdk iphonesimulator -destination "platform=iOS simulator,name=iPhone 11"

      - name: Testing RxRealm tvOS framework
        run: |
          xcodebuild test -scheme 'RxRealm tvOS' -project 'RxRealm.xcodeproj' -destination "platform=tvOS simulator,name=Apple TV 4K"

      - name: Testing RxRealm macOS framework
        run: |
          xcodebuild test -scheme 'RxRealm macOS' -project 'RxRealm.xcodeproj'

      - name: Build Cocoapods iOS Demo
        run: |
          set -eo pipefail
          cd Examples
          export RELEASE_VERSION="$(git describe --abbrev=0 | tr -d '\n')"
          RELEASE_VERSION=${RELEASE_VERSION:1}
          xcodegen
          pod install --repo-update
          xcodebuild build -scheme 'RxRealmDemo-iOS' -workspace 'RxRealmDemo.xcworkspace' -sdk iphonesimulator -destination "platform=iOS simulator,name=iPhone 11"
